import abc
from typing import Any

from core.session_manager.session import Session


class AgentBase(abc.ABC):
    """
    Base abstract class for all agents.

    An agent is responsible for processing user input, optionally maintaining
    session state, and producing a response using a model or custom logic.

    Subclasses must implement the `step` method, which defines the core
    behavior of the agent.
    """

    def __init__(self):
        """
        Initialize the agent.

        This base constructor does not require parameters, but subclasses
        may extend it to include model configuration, API clients, etc.
        """
        pass

    def preprocess(self, message: str, session: Session) -> Any:
        """
        Preprocess the incoming user message before passing it to the model.

        This method can be overridden to apply transformations such as:
        - Prompt formatting
        - Tokenization
        - Context enrichment
        - Input validation

        Args:
            message (str): The raw user input message.
            session (Session): The current session context.

        Returns:
            Any: The processed input. By default, returns the original message.
        """
        return message

    def postprocess(self, message: Any, session: Session) -> Any:
        """
        Postprocess the output generated by the model.

        This method can be overridden to apply transformations such as:
        - Formatting the response
        - Cleaning or parsing output (e.g., JSON parsing)
        - Logging or auditing
        - Updating session state

        Args:
            message (Any): The raw output from the model or step method.
            session (Session): The current session context.

        Returns:
            Any: The processed output. By default, returns the original message.
        """
        return message

    @abc.abstractmethod
    def step(self, message: str, session: Session) -> Any:
        """
        Execute a single step of the agent.

        This is the core method that must be implemented by all subclasses.
        It defines how the agent:
        - Processes the input
        - Interacts with a model (if applicable)
        - Produces a response

        Args:
            message (str): The input message from the user.
            session (Session): The current session context.

        Returns:
            Any: The agent's response.
        """
        raise NotImplementedError("Subclasses must implement the step method")


class AgentWithInferencerBase(AgentBase, abc.ABC):
    def __init__(self, inferencer: Any):
        super().__init__()
        self.inferencer = inferencer
